/** Curated SA townships/suburbs list (alphabetical). */
export const TOWNSHIPS: string[] = [
  "Alexandra, Johannesburg",
  "Atteridgeville, Pretoria",
  "Belhar, Cape Town",
  "Bloemfontein Central",
  "Botshabelo, Free State",
  "Bridgetown, Cape Town",
  "Centurion, Pretoria",
  "Chatsworth, Durban",
  "Daveyton, Ekurhuleni",
  "Diepkloof, Soweto",
  "Diepsloot, Johannesburg",
  "Dobsonville, Soweto",
  "Durban Central",
  "East London Central",
  "Eldorado Park, Johannesburg",
  "Embalenhle, Mpumalanga",
  "Etwatwa, Ekurhuleni",
  "Galeshewe, Kimberley",
  "Gugulethu, Cape Town",
  "Hammanskraal, Pretoria",
  "Inanda, Durban",
  "KaNyamazane, Mpumalanga",
  "Katlehong, Ekurhuleni",
  "Kayamandi, Stellenbosch",
  "Khayelitsha, Cape Town",
  "Kimberley Central",
  "Kraaifontein, Cape Town",
  "Kwa-Thema, Springs",
  "KwaMashu, Durban",
  "Lamontville, Durban",
  "Langa, Cape Town",
  "Mabopane, Pretoria",
  "Mamelodi, Pretoria",
  "Mdantsane, East London",
  "Mfuleni, Cape Town",
  "Mhluzi, Middelburg",
  "Mitchells Plain, Cape Town",
  "Mlazi, Durban",
  "Mohlakeng, Randfontein",
  "Motherwell, Port Elizabeth",
  "Nelspruit Central",
  "Nyanga, Cape Town",
  "Orange Farm, Johannesburg",
  "Orlando East, Soweto",
  "Orlando West, Soweto",
  "Phoenix, Durban",
  "Pietermaritzburg Central",
  "Pimville, Soweto",
  "Polokwane Central",
  "Port Elizabeth Central",
  "Pretoria Central",
  "Protea Glen, Soweto",
  "Randburg, Johannesburg",
  "Roodepoort, Johannesburg",
  "Rustenburg Central",
  "Sandton, Johannesburg",
  "Sebokeng, Vereeniging",
  "Sharpeville, Vereeniging",
  "Soshanguve, Pretoria",
  "Tembisa, Ekurhuleni",
  "Thohoyandou, Limpopo",
  "Thokoza, Ekurhuleni",
  "Tsakane, Brakpan",
  "Umlazi, Durban",
  "Vosloorus, Ekurhuleni",
  "Welkom Central",
  "Witbank Central",
  "Wynberg, Cape Town",
  "Zola, Soweto",
];