/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as ProfileRewardsRouteImport } from './routes/profile.rewards'
import { Route as ProfileReportsRouteImport } from './routes/profile.reports'
import { Route as ProfilePrivacySecurityRouteImport } from './routes/profile.privacy-security'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ChatsIdRouteImport } from './routes/chats.$id'
import { Route as CasesWantedRouteImport } from './routes/cases.wanted'
import { Route as CasesMissingRouteImport } from './routes/cases.missing'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as CasesWantedIdRouteImport } from './routes/cases.wanted.$id'
import { Route as CasesMissingIdRouteImport } from './routes/cases.missing.$id'
import { Route as ApiPublicHooksClusterSweepRouteImport } from './routes/api/public/hooks/cluster-sweep'
import { Route as ApiPublicHooksCampaignDispatchRouteImport } from './routes/api/public/hooks/campaign-dispatch'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRewardsRoute = ProfileRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileReportsRoute = ProfileReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePrivacySecurityRoute = ProfilePrivacySecurityRouteImport.update({
  id: '/privacy-security',
  path: '/privacy-security',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfileRoute,
} as any)
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatsRoute,
} as any)
const CasesWantedRoute = CasesWantedRouteImport.update({
  id: '/cases/wanted',
  path: '/cases/wanted',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesMissingRoute = CasesMissingRouteImport.update({
  id: '/cases/missing',
  path: '/cases/missing',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CasesWantedIdRoute = CasesWantedIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CasesWantedRoute,
} as any)
const CasesMissingIdRoute = CasesMissingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CasesMissingRoute,
} as any)
const ApiPublicHooksClusterSweepRoute =
  ApiPublicHooksClusterSweepRouteImport.update({
    id: '/api/public/hooks/cluster-sweep',
    path: '/api/public/hooks/cluster-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCampaignDispatchRoute =
  ApiPublicHooksCampaignDispatchRouteImport.update({
    id: '/api/public/hooks/campaign-dispatch',
    path: '/api/public/hooks/campaign-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/report': typeof ReportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/cases/missing': typeof CasesMissingRouteWithChildren
  '/cases/wanted': typeof CasesWantedRouteWithChildren
  '/chats/$id': typeof ChatsIdRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy-security': typeof ProfilePrivacySecurityRoute
  '/profile/reports': typeof ProfileReportsRoute
  '/profile/rewards': typeof ProfileRewardsRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/cases/missing/$id': typeof CasesMissingIdRoute
  '/cases/wanted/$id': typeof CasesWantedIdRoute
  '/api/public/hooks/campaign-dispatch': typeof ApiPublicHooksCampaignDispatchRoute
  '/api/public/hooks/cluster-sweep': typeof ApiPublicHooksClusterSweepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/report': typeof ReportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/cases/missing': typeof CasesMissingRouteWithChildren
  '/cases/wanted': typeof CasesWantedRouteWithChildren
  '/chats/$id': typeof ChatsIdRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy-security': typeof ProfilePrivacySecurityRoute
  '/profile/reports': typeof ProfileReportsRoute
  '/profile/rewards': typeof ProfileRewardsRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/cases': typeof CasesIndexRoute
  '/cases/missing/$id': typeof CasesMissingIdRoute
  '/cases/wanted/$id': typeof CasesWantedIdRoute
  '/api/public/hooks/campaign-dispatch': typeof ApiPublicHooksCampaignDispatchRoute
  '/api/public/hooks/cluster-sweep': typeof ApiPublicHooksClusterSweepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/report': typeof ReportRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/cases/missing': typeof CasesMissingRouteWithChildren
  '/cases/wanted': typeof CasesWantedRouteWithChildren
  '/chats/$id': typeof ChatsIdRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy-security': typeof ProfilePrivacySecurityRoute
  '/profile/reports': typeof ProfileReportsRoute
  '/profile/rewards': typeof ProfileRewardsRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/cases/missing/$id': typeof CasesMissingIdRoute
  '/cases/wanted/$id': typeof CasesWantedIdRoute
  '/api/public/hooks/campaign-dispatch': typeof ApiPublicHooksCampaignDispatchRoute
  '/api/public/hooks/cluster-sweep': typeof ApiPublicHooksClusterSweepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/auth'
    | '/chats'
    | '/profile'
    | '/report'
    | '/dashboard'
    | '/campaigns/$id'
    | '/cases/missing'
    | '/cases/wanted'
    | '/chats/$id'
    | '/profile/notifications'
    | '/profile/privacy-security'
    | '/profile/reports'
    | '/profile/rewards'
    | '/campaigns/'
    | '/cases/'
    | '/cases/missing/$id'
    | '/cases/wanted/$id'
    | '/api/public/hooks/campaign-dispatch'
    | '/api/public/hooks/cluster-sweep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/auth'
    | '/chats'
    | '/profile'
    | '/report'
    | '/dashboard'
    | '/campaigns/$id'
    | '/cases/missing'
    | '/cases/wanted'
    | '/chats/$id'
    | '/profile/notifications'
    | '/profile/privacy-security'
    | '/profile/reports'
    | '/profile/rewards'
    | '/campaigns'
    | '/cases'
    | '/cases/missing/$id'
    | '/cases/wanted/$id'
    | '/api/public/hooks/campaign-dispatch'
    | '/api/public/hooks/cluster-sweep'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activity'
    | '/auth'
    | '/chats'
    | '/profile'
    | '/report'
    | '/_authenticated/dashboard'
    | '/campaigns/$id'
    | '/cases/missing'
    | '/cases/wanted'
    | '/chats/$id'
    | '/profile/notifications'
    | '/profile/privacy-security'
    | '/profile/reports'
    | '/profile/rewards'
    | '/campaigns/'
    | '/cases/'
    | '/cases/missing/$id'
    | '/cases/wanted/$id'
    | '/api/public/hooks/campaign-dispatch'
    | '/api/public/hooks/cluster-sweep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ReportRoute: typeof ReportRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  CasesMissingRoute: typeof CasesMissingRouteWithChildren
  CasesWantedRoute: typeof CasesWantedRouteWithChildren
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CasesIndexRoute: typeof CasesIndexRoute
  ApiPublicHooksCampaignDispatchRoute: typeof ApiPublicHooksCampaignDispatchRoute
  ApiPublicHooksClusterSweepRoute: typeof ApiPublicHooksClusterSweepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/rewards': {
      id: '/profile/rewards'
      path: '/rewards'
      fullPath: '/profile/rewards'
      preLoaderRoute: typeof ProfileRewardsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/reports': {
      id: '/profile/reports'
      path: '/reports'
      fullPath: '/profile/reports'
      preLoaderRoute: typeof ProfileReportsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/privacy-security': {
      id: '/profile/privacy-security'
      path: '/privacy-security'
      fullPath: '/profile/privacy-security'
      preLoaderRoute: typeof ProfilePrivacySecurityRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/cases/wanted': {
      id: '/cases/wanted'
      path: '/cases/wanted'
      fullPath: '/cases/wanted'
      preLoaderRoute: typeof CasesWantedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/missing': {
      id: '/cases/missing'
      path: '/cases/missing'
      fullPath: '/cases/missing'
      preLoaderRoute: typeof CasesMissingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cases/wanted/$id': {
      id: '/cases/wanted/$id'
      path: '/$id'
      fullPath: '/cases/wanted/$id'
      preLoaderRoute: typeof CasesWantedIdRouteImport
      parentRoute: typeof CasesWantedRoute
    }
    '/cases/missing/$id': {
      id: '/cases/missing/$id'
      path: '/$id'
      fullPath: '/cases/missing/$id'
      preLoaderRoute: typeof CasesMissingIdRouteImport
      parentRoute: typeof CasesMissingRoute
    }
    '/api/public/hooks/cluster-sweep': {
      id: '/api/public/hooks/cluster-sweep'
      path: '/api/public/hooks/cluster-sweep'
      fullPath: '/api/public/hooks/cluster-sweep'
      preLoaderRoute: typeof ApiPublicHooksClusterSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/campaign-dispatch': {
      id: '/api/public/hooks/campaign-dispatch'
      path: '/api/public/hooks/campaign-dispatch'
      fullPath: '/api/public/hooks/campaign-dispatch'
      preLoaderRoute: typeof ApiPublicHooksCampaignDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ChatsRouteChildren {
  ChatsIdRoute: typeof ChatsIdRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsIdRoute: ChatsIdRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

interface ProfileRouteChildren {
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfilePrivacySecurityRoute: typeof ProfilePrivacySecurityRoute
  ProfileReportsRoute: typeof ProfileReportsRoute
  ProfileRewardsRoute: typeof ProfileRewardsRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfilePrivacySecurityRoute: ProfilePrivacySecurityRoute,
  ProfileReportsRoute: ProfileReportsRoute,
  ProfileRewardsRoute: ProfileRewardsRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface CasesMissingRouteChildren {
  CasesMissingIdRoute: typeof CasesMissingIdRoute
}

const CasesMissingRouteChildren: CasesMissingRouteChildren = {
  CasesMissingIdRoute: CasesMissingIdRoute,
}

const CasesMissingRouteWithChildren = CasesMissingRoute._addFileChildren(
  CasesMissingRouteChildren,
)

interface CasesWantedRouteChildren {
  CasesWantedIdRoute: typeof CasesWantedIdRoute
}

const CasesWantedRouteChildren: CasesWantedRouteChildren = {
  CasesWantedIdRoute: CasesWantedIdRoute,
}

const CasesWantedRouteWithChildren = CasesWantedRoute._addFileChildren(
  CasesWantedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ReportRoute: ReportRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  CasesMissingRoute: CasesMissingRouteWithChildren,
  CasesWantedRoute: CasesWantedRouteWithChildren,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CasesIndexRoute: CasesIndexRoute,
  ApiPublicHooksCampaignDispatchRoute: ApiPublicHooksCampaignDispatchRoute,
  ApiPublicHooksClusterSweepRoute: ApiPublicHooksClusterSweepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
