/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as ReportRouteImport } from './routes/report'
import { Route as MapRouteImport } from './routes/map'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ChatsIndexRouteImport } from './routes/chats.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProfileRewardsRouteImport } from './routes/profile.rewards'
import { Route as ProfileReportsRouteImport } from './routes/profile.reports'
import { Route as ProfilePrivacySecurityRouteImport } from './routes/profile.privacy-security'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ProfileLanguageRouteImport } from './routes/profile.language'
import { Route as ChatsIdRouteImport } from './routes/chats.$id'
import { Route as CasesWantedRouteImport } from './routes/cases.wanted'
import { Route as CasesMissingRouteImport } from './routes/cases.missing'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminCasesRouteImport } from './routes/admin.cases'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as CasesWantedIdRouteImport } from './routes/cases.wanted.$id'
import { Route as CasesMissingIdRouteImport } from './routes/cases.missing.$id'
import { Route as AdminReportReportIdRouteImport } from './routes/admin.report.$reportId'
import { Route as ApiPublicHooksClusterSweepRouteImport } from './routes/api/public/hooks/cluster-sweep'
import { Route as ApiPublicHooksCampaignDispatchRouteImport } from './routes/api/public/hooks/campaign-dispatch'

const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileRewardsRoute = ProfileRewardsRouteImport.update({
  id: '/profile/rewards',
  path: '/profile/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileReportsRoute = ProfileReportsRouteImport.update({
  id: '/profile/reports',
  path: '/profile/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePrivacySecurityRoute = ProfilePrivacySecurityRouteImport.update({
  id: '/profile/privacy-security',
  path: '/profile/privacy-security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/profile/notifications',
  path: '/profile/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileLanguageRoute = ProfileLanguageRouteImport.update({
  id: '/profile/language',
  path: '/profile/language',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesWantedRoute = CasesWantedRouteImport.update({
  id: '/cases/wanted',
  path: '/cases/wanted',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesMissingRoute = CasesMissingRouteImport.update({
  id: '/cases/missing',
  path: '/cases/missing',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CasesWantedIdRoute = CasesWantedIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CasesWantedRoute,
} as any)
const CasesMissingIdRoute = CasesMissingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CasesMissingRoute,
} as any)
const AdminReportReportIdRoute = AdminReportReportIdRouteImport.update({
  id: '/report/$reportId',
  path: '/report/$reportId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksClusterSweepRoute =
  ApiPublicHooksClusterSweepRouteImport.update({
    id: '/api/public/hooks/cluster-sweep',
    path: '/api/public/hooks/cluster-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCampaignDispatchRoute =
  ApiPublicHooksCampaignDispatchRouteImport.update({
    id: '/api/public/hooks/campaign-dispatch',
    path: '/api/public/hooks/campaign-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/stations': typeof StationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/cases/missing': typeof CasesMissingRouteWithChildren
  '/cases/wanted': typeof CasesWantedRouteWithChildren
  '/chats/$id': typeof ChatsIdRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy-security': typeof ProfilePrivacySecurityRoute
  '/profile/reports': typeof ProfileReportsRoute
  '/profile/rewards': typeof ProfileRewardsRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/report/$reportId': typeof AdminReportReportIdRoute
  '/cases/missing/$id': typeof CasesMissingIdRoute
  '/cases/wanted/$id': typeof CasesWantedIdRoute
  '/api/public/hooks/campaign-dispatch': typeof ApiPublicHooksCampaignDispatchRoute
  '/api/public/hooks/cluster-sweep': typeof ApiPublicHooksClusterSweepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/stations': typeof StationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/cases/missing': typeof CasesMissingRouteWithChildren
  '/cases/wanted': typeof CasesWantedRouteWithChildren
  '/chats/$id': typeof ChatsIdRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy-security': typeof ProfilePrivacySecurityRoute
  '/profile/reports': typeof ProfileReportsRoute
  '/profile/rewards': typeof ProfileRewardsRoute
  '/admin': typeof AdminIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/cases': typeof CasesIndexRoute
  '/chats': typeof ChatsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/report/$reportId': typeof AdminReportReportIdRoute
  '/cases/missing/$id': typeof CasesMissingIdRoute
  '/cases/wanted/$id': typeof CasesWantedIdRoute
  '/api/public/hooks/campaign-dispatch': typeof ApiPublicHooksCampaignDispatchRoute
  '/api/public/hooks/cluster-sweep': typeof ApiPublicHooksClusterSweepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/stations': typeof StationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/cases/missing': typeof CasesMissingRouteWithChildren
  '/cases/wanted': typeof CasesWantedRouteWithChildren
  '/chats/$id': typeof ChatsIdRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/privacy-security': typeof ProfilePrivacySecurityRoute
  '/profile/reports': typeof ProfileReportsRoute
  '/profile/rewards': typeof ProfileRewardsRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/report/$reportId': typeof AdminReportReportIdRoute
  '/cases/missing/$id': typeof CasesMissingIdRoute
  '/cases/wanted/$id': typeof CasesWantedIdRoute
  '/api/public/hooks/campaign-dispatch': typeof ApiPublicHooksCampaignDispatchRoute
  '/api/public/hooks/cluster-sweep': typeof ApiPublicHooksClusterSweepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin'
    | '/auth'
    | '/map'
    | '/report'
    | '/stations'
    | '/dashboard'
    | '/admin/analytics'
    | '/admin/campaigns'
    | '/admin/cases'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/settings'
    | '/campaigns/$id'
    | '/cases/missing'
    | '/cases/wanted'
    | '/chats/$id'
    | '/profile/language'
    | '/profile/notifications'
    | '/profile/privacy-security'
    | '/profile/reports'
    | '/profile/rewards'
    | '/admin/'
    | '/campaigns/'
    | '/cases/'
    | '/chats/'
    | '/profile/'
    | '/admin/report/$reportId'
    | '/cases/missing/$id'
    | '/cases/wanted/$id'
    | '/api/public/hooks/campaign-dispatch'
    | '/api/public/hooks/cluster-sweep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/auth'
    | '/map'
    | '/report'
    | '/stations'
    | '/dashboard'
    | '/admin/analytics'
    | '/admin/campaigns'
    | '/admin/cases'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/settings'
    | '/campaigns/$id'
    | '/cases/missing'
    | '/cases/wanted'
    | '/chats/$id'
    | '/profile/language'
    | '/profile/notifications'
    | '/profile/privacy-security'
    | '/profile/reports'
    | '/profile/rewards'
    | '/admin'
    | '/campaigns'
    | '/cases'
    | '/chats'
    | '/profile'
    | '/admin/report/$reportId'
    | '/cases/missing/$id'
    | '/cases/wanted/$id'
    | '/api/public/hooks/campaign-dispatch'
    | '/api/public/hooks/cluster-sweep'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activity'
    | '/admin'
    | '/auth'
    | '/map'
    | '/report'
    | '/stations'
    | '/_authenticated/dashboard'
    | '/admin/analytics'
    | '/admin/campaigns'
    | '/admin/cases'
    | '/admin/reports'
    | '/admin/rewards'
    | '/admin/settings'
    | '/campaigns/$id'
    | '/cases/missing'
    | '/cases/wanted'
    | '/chats/$id'
    | '/profile/language'
    | '/profile/notifications'
    | '/profile/privacy-security'
    | '/profile/reports'
    | '/profile/rewards'
    | '/admin/'
    | '/campaigns/'
    | '/cases/'
    | '/chats/'
    | '/profile/'
    | '/admin/report/$reportId'
    | '/cases/missing/$id'
    | '/cases/wanted/$id'
    | '/api/public/hooks/campaign-dispatch'
    | '/api/public/hooks/cluster-sweep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  MapRoute: typeof MapRoute
  ReportRoute: typeof ReportRoute
  StationsRoute: typeof StationsRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  CasesMissingRoute: typeof CasesMissingRouteWithChildren
  CasesWantedRoute: typeof CasesWantedRouteWithChildren
  ChatsIdRoute: typeof ChatsIdRoute
  ProfileLanguageRoute: typeof ProfileLanguageRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfilePrivacySecurityRoute: typeof ProfilePrivacySecurityRoute
  ProfileReportsRoute: typeof ProfileReportsRoute
  ProfileRewardsRoute: typeof ProfileRewardsRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CasesIndexRoute: typeof CasesIndexRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ApiPublicHooksCampaignDispatchRoute: typeof ApiPublicHooksCampaignDispatchRoute
  ApiPublicHooksClusterSweepRoute: typeof ApiPublicHooksClusterSweepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/rewards': {
      id: '/profile/rewards'
      path: '/profile/rewards'
      fullPath: '/profile/rewards'
      preLoaderRoute: typeof ProfileRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/reports': {
      id: '/profile/reports'
      path: '/profile/reports'
      fullPath: '/profile/reports'
      preLoaderRoute: typeof ProfileReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/privacy-security': {
      id: '/profile/privacy-security'
      path: '/profile/privacy-security'
      fullPath: '/profile/privacy-security'
      preLoaderRoute: typeof ProfilePrivacySecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/profile/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/language': {
      id: '/profile/language'
      path: '/profile/language'
      fullPath: '/profile/language'
      preLoaderRoute: typeof ProfileLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/wanted': {
      id: '/cases/wanted'
      path: '/cases/wanted'
      fullPath: '/cases/wanted'
      preLoaderRoute: typeof CasesWantedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/missing': {
      id: '/cases/missing'
      path: '/cases/missing'
      fullPath: '/cases/missing'
      preLoaderRoute: typeof CasesMissingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cases/wanted/$id': {
      id: '/cases/wanted/$id'
      path: '/$id'
      fullPath: '/cases/wanted/$id'
      preLoaderRoute: typeof CasesWantedIdRouteImport
      parentRoute: typeof CasesWantedRoute
    }
    '/cases/missing/$id': {
      id: '/cases/missing/$id'
      path: '/$id'
      fullPath: '/cases/missing/$id'
      preLoaderRoute: typeof CasesMissingIdRouteImport
      parentRoute: typeof CasesMissingRoute
    }
    '/admin/report/$reportId': {
      id: '/admin/report/$reportId'
      path: '/report/$reportId'
      fullPath: '/admin/report/$reportId'
      preLoaderRoute: typeof AdminReportReportIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/cluster-sweep': {
      id: '/api/public/hooks/cluster-sweep'
      path: '/api/public/hooks/cluster-sweep'
      fullPath: '/api/public/hooks/cluster-sweep'
      preLoaderRoute: typeof ApiPublicHooksClusterSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/campaign-dispatch': {
      id: '/api/public/hooks/campaign-dispatch'
      path: '/api/public/hooks/campaign-dispatch'
      fullPath: '/api/public/hooks/campaign-dispatch'
      preLoaderRoute: typeof ApiPublicHooksCampaignDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCasesRoute: typeof AdminCasesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReportReportIdRoute: typeof AdminReportReportIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCasesRoute: AdminCasesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReportReportIdRoute: AdminReportReportIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CasesMissingRouteChildren {
  CasesMissingIdRoute: typeof CasesMissingIdRoute
}

const CasesMissingRouteChildren: CasesMissingRouteChildren = {
  CasesMissingIdRoute: CasesMissingIdRoute,
}

const CasesMissingRouteWithChildren = CasesMissingRoute._addFileChildren(
  CasesMissingRouteChildren,
)

interface CasesWantedRouteChildren {
  CasesWantedIdRoute: typeof CasesWantedIdRoute
}

const CasesWantedRouteChildren: CasesWantedRouteChildren = {
  CasesWantedIdRoute: CasesWantedIdRoute,
}

const CasesWantedRouteWithChildren = CasesWantedRoute._addFileChildren(
  CasesWantedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  MapRoute: MapRoute,
  ReportRoute: ReportRoute,
  StationsRoute: StationsRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  CasesMissingRoute: CasesMissingRouteWithChildren,
  CasesWantedRoute: CasesWantedRouteWithChildren,
  ChatsIdRoute: ChatsIdRoute,
  ProfileLanguageRoute: ProfileLanguageRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfilePrivacySecurityRoute: ProfilePrivacySecurityRoute,
  ProfileReportsRoute: ProfileReportsRoute,
  ProfileRewardsRoute: ProfileRewardsRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CasesIndexRoute: CasesIndexRoute,
  ChatsIndexRoute: ChatsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ApiPublicHooksCampaignDispatchRoute: ApiPublicHooksCampaignDispatchRoute,
  ApiPublicHooksClusterSweepRoute: ApiPublicHooksClusterSweepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
