
-- Enums
CREATE TYPE public.danger_level AS ENUM ('high', 'medium', 'low');
CREATE TYPE public.disappearance_circumstance AS ENUM ('voluntary', 'family_conflict', 'endangered', 'medical', 'unknown');
CREATE TYPE public.case_status AS ENUM ('active', 'found', 'closed');

-- WANTED PERSONS
CREATE TABLE public.wanted_persons (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  aliases text[] NOT NULL DEFAULT '{}',
  age integer,
  gender text,
  ethnicity text,
  height_cm integer,
  weight_kg integer,
  build text,
  hair_color text,
  eye_color text,
  complexion text,
  distinguishing_features text[] NOT NULL DEFAULT '{}',
  crimes jsonb NOT NULL DEFAULT '[]'::jsonb,
  crime_category text,
  danger_level public.danger_level NOT NULL DEFAULT 'medium',
  armed boolean NOT NULL DEFAULT false,
  warrant_number text,
  investigating_officer text,
  station text,
  last_seen_location text,
  last_seen_at timestamptz,
  last_seen_notes text,
  known_associates text[] NOT NULL DEFAULT '{}',
  known_hangouts text[] NOT NULL DEFAULT '{}',
  vehicle text,
  reward_amount numeric,
  photos text[] NOT NULL DEFAULT '{}',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.wanted_persons TO anon, authenticated;
GRANT ALL ON public.wanted_persons TO service_role;
ALTER TABLE public.wanted_persons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Wanted persons: public can view active" ON public.wanted_persons
  FOR SELECT TO anon, authenticated USING (is_active = true);

CREATE TRIGGER set_wanted_persons_updated_at
  BEFORE UPDATE ON public.wanted_persons
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX idx_wanted_danger ON public.wanted_persons(danger_level);
CREATE INDEX idx_wanted_category ON public.wanted_persons(crime_category);
CREATE INDEX idx_wanted_location ON public.wanted_persons(last_seen_location);
CREATE INDEX idx_wanted_created ON public.wanted_persons(created_at DESC);
CREATE INDEX idx_wanted_name ON public.wanted_persons USING gin (to_tsvector('english', full_name));

-- MISSING PERSONS
CREATE TABLE public.missing_persons (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  age_at_disappearance integer,
  gender text,
  ethnicity text,
  height_cm integer,
  weight_kg integer,
  build text,
  hair_color text,
  eye_color text,
  complexion text,
  distinguishing_features text[] NOT NULL DEFAULT '{}',
  medical_conditions text[] NOT NULL DEFAULT '{}',
  cognitive_impairment boolean NOT NULL DEFAULT false,
  special_needs text[] NOT NULL DEFAULT '{}',
  circumstances public.disappearance_circumstance NOT NULL DEFAULT 'unknown',
  circumstances_narrative text,
  last_seen_location text,
  last_seen_at timestamptz,
  last_seen_clothing text,
  possessions text[] NOT NULL DEFAULT '{}',
  vulnerability_indicators text[] NOT NULL DEFAULT '{}',
  is_endangered boolean NOT NULL DEFAULT false,
  family_contact_name text,
  family_contact_phone text,
  photos text[] NOT NULL DEFAULT '{}',
  case_status public.case_status NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.missing_persons TO anon, authenticated;
GRANT ALL ON public.missing_persons TO service_role;
ALTER TABLE public.missing_persons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Missing persons: public can view active" ON public.missing_persons
  FOR SELECT TO anon, authenticated USING (case_status = 'active');

CREATE TRIGGER set_missing_persons_updated_at
  BEFORE UPDATE ON public.missing_persons
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX idx_missing_endangered ON public.missing_persons(is_endangered);
CREATE INDEX idx_missing_age ON public.missing_persons(age_at_disappearance);
CREATE INDEX idx_missing_location ON public.missing_persons(last_seen_location);
CREATE INDEX idx_missing_last_seen ON public.missing_persons(last_seen_at DESC);
CREATE INDEX idx_missing_circumstances ON public.missing_persons(circumstances);
CREATE INDEX idx_missing_name ON public.missing_persons USING gin (to_tsvector('english', full_name));

-- =====================================
-- SEED: WANTED PERSONS (~50)
-- =====================================
INSERT INTO public.wanted_persons
(full_name, aliases, age, gender, ethnicity, height_cm, weight_kg, build, hair_color, eye_color, complexion,
 distinguishing_features, crimes, crime_category, danger_level, armed,
 warrant_number, investigating_officer, station, last_seen_location, last_seen_at, last_seen_notes,
 known_associates, known_hangouts, vehicle, reward_amount, photos, created_at)
VALUES
('Sipho Mthembu', ARRAY['The Hawk','Bra Sipho'], 34, 'Male', 'Black African', 182, 88, 'Athletic', 'Black', 'Brown', 'Dark',
 ARRAY['Snake tattoo on left forearm','Scar above right eye'],
 '[{"charge":"Armed Robbery","date":"2026-04-12","severity":"high"},{"charge":"Attempted Murder","date":"2026-03-01","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'JHB-2026-001847','Detective Naledi Khumalo','Johannesburg Central','Johannesburg CBD', now() - interval '8 days',
 'Spotted fleeing Sandton City parking. Armed with handgun.',
 ARRAY['Unknown male, 1.75m, red hoodie'], ARRAY['Blaze Nightclub Sandton','JHB taxi ranks'], 'Silver Toyota Corolla NP 22 GJX GP', 50000,
 ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80'], now() - interval '10 days'),

('Jacob van der Merwe', ARRAY['Jaco'], 41, 'Male', 'White', 178, 95, 'Heavy', 'Blonde', 'Blue', 'Fair',
 ARRAY['Full sleeve tattoo right arm','Missing left pinky finger'],
 '[{"charge":"Fraud","date":"2026-02-15","severity":"medium"},{"charge":"Money Laundering","date":"2026-01-20","severity":"medium"}]'::jsonb,
 'Fraud','medium', false,
 'PTA-2026-008812','Detective Pieter Botha','Pretoria Central','Pretoria East', now() - interval '21 days',
 'Last seen leaving residential complex in BMW X5.',
 ARRAY['Business partner Kobus Steyn'], ARRAY['Menlyn Park','Waterkloof Country Club'], 'White BMW X5 GP CA 999 GP', 25000,
 ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80'], now() - interval '25 days'),

('Andile Dlamini', ARRAY[]::text[], 28, 'Male', 'Black African', 175, 72, 'Slim', 'Black', 'Brown', 'Medium',
 ARRAY['Teardrop tattoo under left eye'],
 '[{"charge":"Armed Robbery","date":"2026-05-20","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'SOW-2026-004421','Detective Lerato Mokoena','Soweto','Soweto', now() - interval '2 days',
 'Robbed Pick n Pay armed with shotgun.',
 ARRAY[]::text[], ARRAY['Maponya Mall','Vilakazi Street'], NULL, 15000,
 ARRAY['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&q=80'], now() - interval '3 days'),

('Themba Ngcobo', ARRAY['T-Boz'], 26, 'Male', 'Black African', 170, 68, 'Slim', 'Black', 'Brown', 'Dark',
 ARRAY['Gold front teeth','Cross tattoo on neck'],
 '[{"charge":"Drug Trafficking","date":"2026-04-30","severity":"high"}]'::jsonb,
 'Drug Offenses','high', true,
 'DBN-2026-007734','Detective Sandile Zulu','Durban Central','Durban Point', now() - interval '14 days',
 'Suspected of running drug operation in Point area.',
 ARRAY['Mandla Sithole'], ARRAY['Point Waterfront','Berea taxi rank'], 'Black VW Polo ND 88 KZN', 30000,
 ARRAY['https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&q=80'], now() - interval '15 days'),

('Pieter Nel', ARRAY[]::text[], 52, 'Male', 'White', 180, 102, 'Heavy', 'Grey', 'Green', 'Fair',
 ARRAY['Beard, full grey'],
 '[{"charge":"Embezzlement","date":"2025-11-12","severity":"medium"}]'::jsonb,
 'Fraud','low', false,
 'CPT-2025-099201','Detective Anneline du Plessis','Cape Town Central','Cape Town CBD', now() - interval '90 days',
 'Fled country allegedly via Lesotho border.',
 ARRAY[]::text[], ARRAY['V&A Waterfront','Camps Bay'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1552058544-f2b08422138a?w=600&q=80'], now() - interval '100 days'),

('Bongani Khoza', ARRAY['Bongs'], 31, 'Male', 'Black African', 185, 90, 'Muscular', 'Black', 'Brown', 'Dark',
 ARRAY['Lion tattoo across chest','Scar on left cheek'],
 '[{"charge":"Murder","date":"2026-05-01","severity":"high"},{"charge":"Hijacking","date":"2026-04-15","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'JHB-2026-002201','Detective Naledi Khumalo','Johannesburg Central','Alexandra', now() - interval '6 days',
 'Armed and extremely dangerous. Do not approach.',
 ARRAY['Sipho Mthembu'], ARRAY['Alex taxi rank','Pan Africa Mall'], 'Red Polo Vivo GP', 75000,
 ARRAY['https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&q=80'], now() - interval '7 days'),

('Lerato Mahlangu', ARRAY[]::text[], 29, 'Female', 'Black African', 165, 60, 'Slim', 'Black braids', 'Brown', 'Medium',
 ARRAY['Butterfly tattoo on right shoulder'],
 '[{"charge":"Fraud","date":"2026-03-22","severity":"medium"},{"charge":"Identity Theft","date":"2026-03-10","severity":"medium"}]'::jsonb,
 'Fraud','low', false,
 'PTA-2026-006612','Detective Pieter Botha','Pretoria Central','Centurion', now() - interval '45 days',
 'Operated identity theft ring targeting elderly.',
 ARRAY[]::text[], ARRAY['Centurion Mall'], NULL, 10000,
 ARRAY['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&q=80'], now() - interval '50 days'),

('Mandla Ndlovu', ARRAY['Mandla 9mm'], 38, 'Male', 'Black African', 178, 82, 'Athletic', 'Bald', 'Brown', 'Dark',
 ARRAY['Bald head with scar across crown','Tattoo of 9mm on forearm'],
 '[{"charge":"Cash-in-transit Heist","date":"2026-04-04","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'JHB-2026-001955','Detective Naledi Khumalo','Germiston','Germiston East', now() - interval '20 days',
 'Believed to be planning further CIT heists.',
 ARRAY['Bongani Khoza'], ARRAY['Germiston Lake','East Rand Mall'], 'White Toyota Hilux DC GP', 100000,
 ARRAY['https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&q=80'], now() - interval '22 days'),

('Vusi Mbeki', ARRAY[]::text[], 24, 'Male', 'Black African', 172, 65, 'Slim', 'Black', 'Brown', 'Medium',
 ARRAY['Scar on right hand'],
 '[{"charge":"Burglary","date":"2026-05-18","severity":"medium"}]'::jsonb,
 'Property Crimes','medium', false,
 'SOW-2026-004499','Detective Lerato Mokoena','Soweto','Orlando East', now() - interval '4 days',
 'Burglarised multiple homes in Orlando.',
 ARRAY[]::text[], ARRAY['Orlando Stadium','Vilakazi Street'], NULL, 5000,
 ARRAY['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80'], now() - interval '5 days'),

('Karabo Sithole', ARRAY['KB'], 33, 'Male', 'Black African', 180, 85, 'Athletic', 'Black dreadlocks', 'Brown', 'Dark',
 ARRAY['Long dreadlocks, hip-length','Tribal tattoo on left bicep'],
 '[{"charge":"Assault GBH","date":"2026-05-10","severity":"high"}]'::jsonb,
 'Violent Crimes','high', false,
 'JHB-2026-002088','Detective Naledi Khumalo','Hillbrow','Hillbrow', now() - interval '12 days',
 'Assaulted security guard at nightclub.',
 ARRAY[]::text[], ARRAY['Hillbrow Tower area','Berea'], NULL, 8000,
 ARRAY['https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=600&q=80'], now() - interval '13 days'),

('Riaan Steyn', ARRAY[]::text[], 45, 'Male', 'White', 175, 88, 'Stocky', 'Brown', 'Hazel', 'Fair',
 ARRAY['Moustache, handlebar style'],
 '[{"charge":"Stock Theft","date":"2026-02-28","severity":"medium"}]'::jsonb,
 'Property Crimes','low', false,
 'BFN-2026-003344','Detective Johan Pretorius','Bloemfontein','Bloemfontein North', now() - interval '60 days',
 'Suspected involvement in cattle theft ring.',
 ARRAY[]::text[], ARRAY['Free State farmlands'], 'Toyota Hilux FS', NULL,
 ARRAY['https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=600&q=80'], now() - interval '65 days'),

('Nomvula Mokoena', ARRAY[]::text[], 27, 'Female', 'Black African', 168, 62, 'Athletic', 'Black weave', 'Brown', 'Medium',
 ARRAY['Star tattoo behind right ear'],
 '[{"charge":"Drug Possession","date":"2026-05-05","severity":"medium"}]'::jsonb,
 'Drug Offenses','medium', false,
 'DBN-2026-007811','Detective Sandile Zulu','Durban Central','Umlazi', now() - interval '18 days',
 'Caught with significant quantity of crystal meth.',
 ARRAY['Themba Ngcobo'], ARRAY['Umlazi Mega City'], NULL, 12000,
 ARRAY['https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&q=80'], now() - interval '20 days'),

('Sandile Mthethwa', ARRAY[]::text[], 36, 'Male', 'Black African', 183, 92, 'Heavy', 'Black', 'Brown', 'Dark',
 ARRAY['Gunshot scar on right shoulder'],
 '[{"charge":"Carjacking","date":"2026-05-25","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'PMB-2026-001102','Detective Sandile Zulu','Pietermaritzburg','Pietermaritzburg', now() - interval '1 day',
 'Hijacked vehicle at gunpoint near city centre.',
 ARRAY[]::text[], ARRAY['PMB taxi rank'], NULL, 20000,
 ARRAY['https://images.unsplash.com/photo-1610216705422-caa3fcb6d158?w=600&q=80'], now() - interval '2 days'),

('Tshepo Maboe', ARRAY[]::text[], 30, 'Male', 'Black African', 177, 75, 'Athletic', 'Black', 'Brown', 'Medium',
 ARRAY['Diamond tattoo on right hand'],
 '[{"charge":"Drug Dealing","date":"2026-04-22","severity":"medium"}]'::jsonb,
 'Drug Offenses','medium', false,
 'JHB-2026-002033','Detective Naledi Khumalo','Yeoville','Yeoville', now() - interval '30 days',
 'Operates drug distribution from Yeoville flat.',
 ARRAY[]::text[], ARRAY['Rockey Street','Yeoville market'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1542178243-bc20204b769f?w=600&q=80'], now() - interval '32 days'),

('Johannes Coetzee', ARRAY[]::text[], 49, 'Male', 'White', 182, 98, 'Heavy', 'Brown/grey', 'Blue', 'Fair',
 ARRAY['Tribal sleeve tattoo left arm'],
 '[{"charge":"Tax Evasion","date":"2025-12-10","severity":"medium"}]'::jsonb,
 'Fraud','low', false,
 'CPT-2025-099477','Detective Anneline du Plessis','Cape Town Central','Sea Point', now() - interval '120 days',
 'Believed to be hiding in coastal area.',
 ARRAY[]::text[], ARRAY['Sea Point Promenade'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1480455624313-e29b44bbfde1?w=600&q=80'], now() - interval '130 days'),

('Lwazi Buthelezi', ARRAY['Lwa'], 25, 'Male', 'Black African', 174, 70, 'Slim', 'Black', 'Brown', 'Dark',
 ARRAY['Scar on left forearm'],
 '[{"charge":"Armed Robbery","date":"2026-05-15","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'DBN-2026-007899','Detective Sandile Zulu','Durban Central','Phoenix', now() - interval '9 days',
 'Robbed multiple spaza shops at gunpoint.',
 ARRAY[]::text[], ARRAY['Phoenix Plaza'], NULL, 18000,
 ARRAY['https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?w=600&q=80'], now() - interval '10 days'),

('Mpho Lekota', ARRAY[]::text[], 32, 'Female', 'Black African', 170, 65, 'Athletic', 'Black short', 'Brown', 'Medium',
 ARRAY['Rose tattoo on left ankle'],
 '[{"charge":"Human Trafficking","date":"2026-03-15","severity":"high"}]'::jsonb,
 'Other Crimes','high', false,
 'JHB-2026-001899','Detective Naledi Khumalo','Hillbrow','Hillbrow', now() - interval '75 days',
 'Suspected leader of trafficking network.',
 ARRAY[]::text[], ARRAY['Hillbrow flats'], NULL, 60000,
 ARRAY['https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=600&q=80'], now() - interval '80 days'),

('Sello Dube', ARRAY[]::text[], 39, 'Male', 'Black African', 179, 84, 'Athletic', 'Black', 'Brown', 'Dark',
 ARRAY['Crown tattoo on right wrist'],
 '[{"charge":"Vehicle Theft","date":"2026-04-18","severity":"medium"}]'::jsonb,
 'Property Crimes','medium', false,
 'PTA-2026-006688','Detective Pieter Botha','Mamelodi','Mamelodi East', now() - interval '40 days',
 'Suspected of running chop shop.',
 ARRAY[]::text[], ARRAY['Mamelodi industrial'], NULL, 8000,
 ARRAY['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&q=80'], now() - interval '42 days'),

('Nathi Khumalo', ARRAY[]::text[], 22, 'Male', 'Black African', 171, 63, 'Slim', 'Black', 'Brown', 'Medium',
 ARRAY['Acne scarring on cheeks'],
 '[{"charge":"Theft","date":"2026-05-28","severity":"low"}]'::jsonb,
 'Property Crimes','low', false,
 'SOW-2026-004556','Detective Lerato Mokoena','Soweto','Diepkloof', now() - interval '2 days',
 'Cellphone theft suspect.',
 ARRAY[]::text[], ARRAY['Diepkloof Square'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=600&q=80'], now() - interval '3 days'),

('Frans Pretorius', ARRAY[]::text[], 47, 'Male', 'White', 176, 90, 'Stocky', 'Brown', 'Brown', 'Fair',
 ARRAY['Beard, neatly trimmed'],
 '[{"charge":"Investment Fraud","date":"2025-10-20","severity":"medium"}]'::jsonb,
 'Fraud','medium', false,
 'CPT-2025-098822','Detective Anneline du Plessis','Cape Town Central','Stellenbosch', now() - interval '150 days',
 'Defrauded investors of R20m in Ponzi scheme.',
 ARRAY[]::text[], ARRAY['Stellenbosch wine farms'], NULL, 50000,
 ARRAY['https://images.unsplash.com/photo-1463453091185-61582044d556?w=600&q=80'], now() - interval '160 days'),

('Themba Zulu', ARRAY[]::text[], 35, 'Male', 'Black African', 184, 95, 'Muscular', 'Bald', 'Brown', 'Dark',
 ARRAY['Tribal scar lines on cheeks','Lion tattoo back of head'],
 '[{"charge":"Murder","date":"2026-04-25","severity":"high"},{"charge":"Attempted Murder","date":"2026-04-22","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'DBN-2026-007944','Detective Sandile Zulu','Durban Central','KwaMashu', now() - interval '16 days',
 'Suspected hitman, extremely dangerous.',
 ARRAY[]::text[], ARRAY['KwaMashu hostel'], 'Black BMW 320i ND', 150000,
 ARRAY['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80'], now() - interval '18 days'),

('Zanele Ngubane', ARRAY[]::text[], 28, 'Female', 'Black African', 167, 58, 'Slim', 'Black braids', 'Brown', 'Dark',
 ARRAY['Heart tattoo on right wrist'],
 '[{"charge":"Fraud","date":"2026-03-30","severity":"low"}]'::jsonb,
 'Fraud','low', false,
 'PMB-2026-001188','Detective Sandile Zulu','Pietermaritzburg','PMB Central', now() - interval '55 days',
 'Credit card fraud.',
 ARRAY[]::text[], ARRAY['Liberty Midlands Mall'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&q=80'], now() - interval '58 days'),

('Tebogo Modise', ARRAY[]::text[], 31, 'Male', 'Black African', 178, 80, 'Athletic', 'Black', 'Brown', 'Medium',
 ARRAY['Number 7 tattoo on neck'],
 '[{"charge":"Gang-related Assault","date":"2026-05-12","severity":"high"}]'::jsonb,
 'Violent Crimes','high', false,
 'JHB-2026-002099','Detective Naledi Khumalo','Westbury','Westbury', now() - interval '11 days',
 'Known member of Number 7 gang.',
 ARRAY[]::text[], ARRAY['Westbury','Newclare'], NULL, 15000,
 ARRAY['https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=600&q=80'], now() - interval '12 days'),

('Hennie Vorster', ARRAY[]::text[], 53, 'Male', 'White', 174, 86, 'Stocky', 'Grey', 'Blue', 'Fair',
 ARRAY['Bald patch on crown','Tattoo of dagger on right arm'],
 '[{"charge":"Illegal Firearm Dealing","date":"2026-02-10","severity":"high"}]'::jsonb,
 'Other Crimes','high', true,
 'PTA-2026-006799','Detective Pieter Botha','Pretoria West','Pretoria West', now() - interval '85 days',
 'Suspected of supplying firearms to criminal syndicates.',
 ARRAY[]::text[], ARRAY['Pretoria West industrial'], NULL, 75000,
 ARRAY['https://images.unsplash.com/photo-1521119989659-a83eee488004?w=600&q=80'], now() - interval '90 days'),

('Sibusiso Hadebe', ARRAY[]::text[], 23, 'Male', 'Black African', 173, 66, 'Slim', 'Black', 'Brown', 'Medium',
 ARRAY['Lightning bolt tattoo on neck'],
 '[{"charge":"Burglary","date":"2026-05-30","severity":"medium"}]'::jsonb,
 'Property Crimes','low', false,
 'SOW-2026-004601','Detective Lerato Mokoena','Soweto','Naledi', now() - interval '1 day',
 'Multiple house break-ins in Naledi.',
 ARRAY[]::text[], ARRAY['Naledi'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1605462863863-10d9e47e15ee?w=600&q=80'], now() - interval '2 days'),

('Ayanda Mahlangu', ARRAY[]::text[], 26, 'Female', 'Black African', 169, 64, 'Athletic', 'Black short', 'Brown', 'Dark',
 ARRAY['Sun tattoo on left shoulder'],
 '[{"charge":"Drug Possession with Intent","date":"2026-05-08","severity":"medium"}]'::jsonb,
 'Drug Offenses','medium', false,
 'JHB-2026-002044','Detective Naledi Khumalo','Rosebank','Rosebank', now() - interval '17 days',
 'Caught with cocaine at nightclub.',
 ARRAY[]::text[], ARRAY['Rosebank nightlife'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1554151228-14d9def656e4?w=600&q=80'], now() - interval '19 days'),

('Pieter Du Toit', ARRAY[]::text[], 44, 'Male', 'White', 181, 92, 'Heavy', 'Brown', 'Green', 'Fair',
 ARRAY['Maple leaf tattoo right arm'],
 '[{"charge":"Hijacking","date":"2026-04-08","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'PTA-2026-006712','Detective Pieter Botha','Pretoria Central','Hatfield', now() - interval '50 days',
 'Hijacked vehicle in Hatfield, fled with passengers.',
 ARRAY[]::text[], ARRAY['Hatfield Plaza'], NULL, 30000,
 ARRAY['https://images.unsplash.com/photo-1463453091185-61582044d556?w=600&q=80'], now() - interval '52 days'),

('Mxolisi Gumede', ARRAY[]::text[], 37, 'Male', 'Black African', 181, 87, 'Athletic', 'Black', 'Brown', 'Dark',
 ARRAY['Scar across right eyebrow'],
 '[{"charge":"Armed Robbery","date":"2026-05-22","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'DBN-2026-007988','Detective Sandile Zulu','Durban North','Umhlanga', now() - interval '7 days',
 'Robbed Gateway Mall jewelry store.',
 ARRAY[]::text[], ARRAY['Gateway','Umhlanga Ridge'], 'Silver Honda Civic ND', 40000,
 ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80'], now() - interval '8 days'),

('Refilwe Motaung', ARRAY[]::text[], 30, 'Female', 'Black African', 166, 60, 'Slim', 'Black braids', 'Brown', 'Medium',
 ARRAY['Snake tattoo around right ankle'],
 '[{"charge":"Robbery","date":"2026-04-14","severity":"medium"}]'::jsonb,
 'Violent Crimes','medium', false,
 'JHB-2026-002012','Detective Naledi Khumalo','Bramley','Bramley', now() - interval '48 days',
 'Part of robbery crew targeting motorists.',
 ARRAY[]::text[], ARRAY['Bramley','Wynberg'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&q=80'], now() - interval '50 days'),

('Tumelo Pule', ARRAY[]::text[], 33, 'Male', 'Black African', 176, 78, 'Athletic', 'Black', 'Brown', 'Medium',
 ARRAY['Number tattoo on neck'],
 '[{"charge":"Murder","date":"2026-05-03","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'BFN-2026-003388','Detective Johan Pretorius','Bloemfontein Central','Mangaung', now() - interval '15 days',
 'Suspect in tavern shooting.',
 ARRAY[]::text[], ARRAY['Mangaung','Botshabelo'], NULL, 25000,
 ARRAY['https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&q=80'], now() - interval '16 days'),

('Eduardo Silva', ARRAY['Edi'], 42, 'Male', 'Portuguese', 173, 80, 'Stocky', 'Black', 'Brown', 'Olive',
 ARRAY['Cross tattoo right forearm','Beard, full'],
 '[{"charge":"Money Laundering","date":"2026-01-30","severity":"medium"}]'::jsonb,
 'Fraud','medium', false,
 'JHB-2026-001844','Detective Naledi Khumalo','Bedfordview','Bedfordview', now() - interval '95 days',
 'Laundered proceeds of drug trafficking.',
 ARRAY[]::text[], ARRAY['Bedford Centre','Eastgate'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1542178243-bc20204b769f?w=600&q=80'], now() - interval '100 days'),

('Sizwe Mlangeni', ARRAY[]::text[], 29, 'Male', 'Black African', 180, 82, 'Athletic', 'Black', 'Brown', 'Dark',
 ARRAY['Scorpion tattoo on left forearm'],
 '[{"charge":"Cash-in-transit Robbery","date":"2026-05-18","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'JHB-2026-002112','Detective Naledi Khumalo','Roodepoort','Roodepoort', now() - interval '8 days',
 'Suspected role in CIT heist on N1.',
 ARRAY['Mandla Ndlovu'], ARRAY['Roodepoort','Princess Crossing'], NULL, 80000,
 ARRAY['https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&q=80'], now() - interval '9 days'),

('Naledi Phiri', ARRAY[]::text[], 25, 'Female', 'Black African', 170, 62, 'Slim', 'Black braids', 'Brown', 'Medium',
 ARRAY['Butterfly tattoo on left wrist'],
 '[{"charge":"Internet Fraud","date":"2026-04-02","severity":"low"}]'::jsonb,
 'Fraud','low', false,
 'PTA-2026-006822','Detective Pieter Botha','Centurion','Centurion', now() - interval '60 days',
 'Operating online romance scam.',
 ARRAY[]::text[], ARRAY[]::text[], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&q=80'], now() - interval '62 days'),

('Marius Joubert', ARRAY[]::text[], 38, 'Male', 'White', 177, 85, 'Athletic', 'Brown', 'Blue', 'Fair',
 ARRAY['Cross tattoo on right wrist'],
 '[{"charge":"Assault","date":"2026-05-26","severity":"medium"}]'::jsonb,
 'Violent Crimes','medium', false,
 'CPT-2026-099601','Detective Anneline du Plessis','Cape Town Central','Goodwood', now() - interval '3 days',
 'Pub fight resulting in serious injury.',
 ARRAY[]::text[], ARRAY['Goodwood','Parow'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80'], now() - interval '4 days'),

('Tlhalefang Tau', ARRAY[]::text[], 27, 'Male', 'Black African', 175, 72, 'Slim', 'Black', 'Brown', 'Dark',
 ARRAY['Lion paw tattoo on chest'],
 '[{"charge":"Robbery","date":"2026-05-20","severity":"medium"}]'::jsonb,
 'Violent Crimes','medium', false,
 'BFN-2026-003411','Detective Johan Pretorius','Bloemfontein North','Heidedal', now() - interval '6 days',
 'Suspected in series of street robberies.',
 ARRAY[]::text[], ARRAY['Heidedal'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&q=80'], now() - interval '7 days'),

('Phumzile Khoza', ARRAY[]::text[], 34, 'Female', 'Black African', 172, 70, 'Athletic', 'Black short', 'Brown', 'Dark',
 ARRAY['Tribal tattoo on right shoulder'],
 '[{"charge":"Drug Trafficking","date":"2026-03-28","severity":"high"}]'::jsonb,
 'Drug Offenses','high', false,
 'DBN-2026-008011','Detective Sandile Zulu','Durban Central','Chatsworth', now() - interval '65 days',
 'Suspected courier in international drug ring.',
 ARRAY[]::text[], ARRAY['King Shaka International'], NULL, 45000,
 ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&q=80'], now() - interval '68 days'),

('Daniel Maritz', ARRAY[]::text[], 51, 'Male', 'White', 180, 100, 'Heavy', 'Grey', 'Brown', 'Fair',
 ARRAY['Beard, full grey','Scar on left hand'],
 '[{"charge":"Stock Theft","date":"2026-01-15","severity":"medium"}]'::jsonb,
 'Property Crimes','low', false,
 'BFN-2026-003266','Detective Johan Pretorius','Bloemfontein','Welkom', now() - interval '110 days',
 'Suspected leader of cattle rustling operation.',
 ARRAY[]::text[], ARRAY['Welkom','Virginia'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1463453091185-61582044d556?w=600&q=80'], now() - interval '115 days'),

('Senzo Mabaso', ARRAY[]::text[], 30, 'Male', 'Black African', 179, 80, 'Athletic', 'Black', 'Brown', 'Dark',
 ARRAY['Skull tattoo on right hand'],
 '[{"charge":"Vehicle Hijacking","date":"2026-04-29","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'PMB-2026-001244','Detective Sandile Zulu','Pietermaritzburg','PMB North', now() - interval '20 days',
 'Multiple hijackings in PMB area.',
 ARRAY[]::text[], ARRAY['PMB','Edendale'], NULL, 25000,
 ARRAY['https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?w=600&q=80'], now() - interval '22 days'),

('Lebo Sello', ARRAY[]::text[], 24, 'Female', 'Black African', 165, 58, 'Slim', 'Black braids', 'Brown', 'Medium',
 ARRAY['Heart tattoo on left ankle'],
 '[{"charge":"Theft from Motor Vehicle","date":"2026-05-25","severity":"low"}]'::jsonb,
 'Property Crimes','low', false,
 'JHB-2026-002155','Detective Naledi Khumalo','Sandton','Sandton', now() - interval '4 days',
 'Theft from parked vehicles in Sandton.',
 ARRAY[]::text[], ARRAY['Sandton'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=600&q=80'], now() - interval '5 days'),

('Riyaad Achmat', ARRAY[]::text[], 36, 'Male', 'Cape Coloured', 174, 78, 'Athletic', 'Black', 'Brown', 'Olive',
 ARRAY['Number 28 tattoo on knuckles'],
 '[{"charge":"Gang Violence","date":"2026-04-20","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'CPT-2026-099544','Detective Anneline du Plessis','Mitchells Plain','Mitchells Plain', now() - interval '40 days',
 'Known member of 28s prison gang.',
 ARRAY[]::text[], ARRAY['Mitchells Plain','Manenberg'], NULL, 35000,
 ARRAY['https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&q=80'], now() - interval '42 days'),

('Bra-T Mokoena', ARRAY['Bra T'], 41, 'Male', 'Black African', 184, 96, 'Heavy', 'Bald', 'Brown', 'Dark',
 ARRAY['Bald head with tribal tattoo','Gold tooth'],
 '[{"charge":"Murder","date":"2026-03-12","severity":"high"},{"charge":"Conspiracy","date":"2026-03-10","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'JHB-2026-001922','Detective Naledi Khumalo','Soweto','Meadowlands', now() - interval '75 days',
 'Suspected taxi industry assassin.',
 ARRAY[]::text[], ARRAY['Meadowlands','Dobsonville'], NULL, 120000,
 ARRAY['https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&q=80'], now() - interval '78 days'),

('Kgalalelo Modise', ARRAY[]::text[], 28, 'Male', 'Black African', 176, 74, 'Athletic', 'Black', 'Brown', 'Medium',
 ARRAY['Crown tattoo on left wrist'],
 '[{"charge":"Robbery","date":"2026-05-19","severity":"medium"}]'::jsonb,
 'Violent Crimes','medium', false,
 'PTA-2026-006888','Detective Pieter Botha','Atteridgeville','Atteridgeville', now() - interval '9 days',
 'Robbed taxi drivers at gunpoint.',
 ARRAY[]::text[], ARRAY['Atteridgeville'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=600&q=80'], now() - interval '10 days'),

('Stefan Wilkens', ARRAY[]::text[], 46, 'Male', 'White', 178, 93, 'Heavy', 'Brown', 'Blue', 'Fair',
 ARRAY['Maple leaf tattoo on chest'],
 '[{"charge":"Cybercrime","date":"2026-02-22","severity":"medium"}]'::jsonb,
 'Other Crimes','medium', false,
 'PTA-2026-006744','Detective Pieter Botha','Pretoria Central','Pretoria CBD', now() - interval '80 days',
 'Suspected ringleader of ATM skimming.',
 ARRAY[]::text[], ARRAY[]::text[], NULL, 20000,
 ARRAY['https://images.unsplash.com/photo-1552058544-f2b08422138a?w=600&q=80'], now() - interval '85 days'),

('Lukhanyo Soga', ARRAY[]::text[], 32, 'Male', 'Black African', 178, 78, 'Athletic', 'Black', 'Brown', 'Dark',
 ARRAY['Tribal scarification on cheeks'],
 '[{"charge":"Armed Robbery","date":"2026-05-11","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'CPT-2026-099588','Detective Anneline du Plessis','Khayelitsha','Khayelitsha', now() - interval '12 days',
 'Robbed multiple convenience stores.',
 ARRAY[]::text[], ARRAY['Khayelitsha'], NULL, 22000,
 ARRAY['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80'], now() - interval '13 days'),

('Aisha Patel', ARRAY[]::text[], 29, 'Female', 'Indian South African', 162, 56, 'Slim', 'Black long', 'Brown', 'Olive',
 ARRAY['Henna-style tattoo on right hand'],
 '[{"charge":"Insurance Fraud","date":"2026-03-18","severity":"medium"}]'::jsonb,
 'Fraud','low', false,
 'DBN-2026-007922','Detective Sandile Zulu','Chatsworth','Chatsworth', now() - interval '70 days',
 'Staged vehicle accidents for insurance claims.',
 ARRAY[]::text[], ARRAY['Chatsworth'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&q=80'], now() - interval '72 days'),

('Mongezi Booi', ARRAY[]::text[], 35, 'Male', 'Black African', 181, 86, 'Athletic', 'Black', 'Brown', 'Dark',
 ARRAY['Scar across forehead'],
 '[{"charge":"Assault GBH","date":"2026-05-08","severity":"high"}]'::jsonb,
 'Violent Crimes','high', false,
 'CPT-2026-099655','Detective Anneline du Plessis','Gugulethu','Gugulethu', now() - interval '14 days',
 'Stabbing during tavern altercation.',
 ARRAY[]::text[], ARRAY['Gugulethu','Nyanga'], NULL, 10000,
 ARRAY['https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=600&q=80'], now() - interval '15 days'),

('Wesley Carstens', ARRAY[]::text[], 26, 'Male', 'Cape Coloured', 172, 68, 'Slim', 'Black short', 'Brown', 'Olive',
 ARRAY['Star tattoo behind left ear'],
 '[{"charge":"Drug Possession","date":"2026-05-15","severity":"medium"}]'::jsonb,
 'Drug Offenses','medium', false,
 'CPT-2026-099677','Detective Anneline du Plessis','Mitchells Plain','Mitchells Plain', now() - interval '8 days',
 'Caught dealing tik in residential area.',
 ARRAY['Riyaad Achmat'], ARRAY['Mitchells Plain'], NULL, NULL,
 ARRAY['https://images.unsplash.com/photo-1521119989659-a83eee488004?w=600&q=80'], now() - interval '9 days'),

('Oratile Sebola', ARRAY[]::text[], 31, 'Male', 'Black African', 179, 81, 'Athletic', 'Black short', 'Brown', 'Medium',
 ARRAY['Tribal tattoo on right bicep'],
 '[{"charge":"Hijacking","date":"2026-04-26","severity":"high"}]'::jsonb,
 'Violent Crimes','high', true,
 'JHB-2026-002066','Detective Naledi Khumalo','Tembisa','Tembisa', now() - interval '30 days',
 'Hijacked delivery vehicle, threatened driver.',
 ARRAY[]::text[], ARRAY['Tembisa','Kempton Park'], NULL, 28000,
 ARRAY['https://images.unsplash.com/photo-1610216705422-caa3fcb6d158?w=600&q=80'], now() - interval '32 days'),

('Bheki Mthethwa', ARRAY[]::text[], 38, 'Male', 'Black African', 182, 90, 'Heavy', 'Bald', 'Brown', 'Dark',
 ARRAY['Bald with cross-shaped scar on crown'],
 '[{"charge":"Extortion","date":"2026-04-10","severity":"high"}]'::jsonb,
 'Other Crimes','high', false,
 'DBN-2026-008055','Detective Sandile Zulu','Durban Central','Durban CBD', now() - interval '50 days',
 'Extorting protection money from foreign-owned spazas.',
 ARRAY[]::text[], ARRAY['Durban CBD'], NULL, 35000,
 ARRAY['https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=600&q=80'], now() - interval '52 days'),

('Sophie Naidoo', ARRAY[]::text[], 33, 'Female', 'Indian South African', 168, 63, 'Athletic', 'Black long', 'Brown', 'Olive',
 ARRAY['Lotus tattoo on left shoulder'],
 '[{"charge":"Banking Fraud","date":"2026-02-05","severity":"medium"}]'::jsonb,
 'Fraud','medium', false,
 'DBN-2026-007855','Detective Sandile Zulu','Durban North','Westville', now() - interval '100 days',
 'Inside banker, defrauded clients of R5m.',
 ARRAY[]::text[], ARRAY['Westville','Pinetown'], NULL, 30000,
 ARRAY['https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=600&q=80'], now() - interval '105 days');

-- =====================================
-- SEED: MISSING PERSONS (~30)
-- =====================================
INSERT INTO public.missing_persons
(full_name, age_at_disappearance, gender, ethnicity, height_cm, weight_kg, build,
 hair_color, eye_color, complexion, distinguishing_features,
 medical_conditions, cognitive_impairment, special_needs,
 circumstances, circumstances_narrative,
 last_seen_location, last_seen_at, last_seen_clothing, possessions,
 vulnerability_indicators, is_endangered,
 family_contact_name, family_contact_phone, photos, created_at)
VALUES
('Sarah Mkhize', 16, 'Female', 'Indian South African', 160, 52, 'Slim',
 'Black long', 'Brown', 'Olive', ARRAY['Birthmark on left cheek'],
 ARRAY['Asthma'], false, ARRAY['Requires inhaler'],
 'endangered','Sarah left home for school on the morning of disappearance and never arrived. School reported absence at 10am. Last seen near the taxi rank.',
 'Baragwanath Taxi Rank, Soweto', now() - interval '5 days', 'Green school uniform, white sneakers, red backpack',
 ARRAY['Black school bag with books','Blue umbrella','R50 cash'],
 ARRAY['Minor','Medical condition'], true,
 'Thandi Mkhize (Mother)','+27 82 555 0101',
 ARRAY['https://images.unsplash.com/photo-1542596594-649edbc13630?w=600&q=80'], now() - interval '5 days'),

('Johannes Pretorius', 78, 'Male', 'White', 172, 70, 'Slim',
 'Grey', 'Blue', 'Fair', ARRAY['Hearing aid in right ear','Walking cane'],
 ARRAY['Type 2 Diabetes','Early-stage dementia'], true, ARRAY['Requires daily insulin','Communicates slowly'],
 'medical','Mr Pretorius wandered from his frail care facility during the night staff shift change.',
 'Silverton Frail Care, Pretoria', now() - interval '1 day', 'Blue pyjamas, brown slippers',
 ARRAY[]::text[],
 ARRAY['Elderly','Cognitive impairment','Medical condition'], true,
 'Marie Pretorius (Daughter)','+27 83 555 0102',
 ARRAY['https://images.unsplash.com/photo-1559963110-71b394e7494d?w=600&q=80'], now() - interval '1 day'),

('Lerato Ndlovu', 8, 'Female', 'Black African', 128, 28, 'Slim',
 'Black braids', 'Brown', 'Dark', ARRAY['Gap between front teeth'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'endangered','Lerato was playing outside her grandmother''s home in Diepkloof when she disappeared. Last seen by neighbour.',
 'Diepkloof Zone 5, Soweto', now() - interval '3 days', 'Pink dress, white sandals, yellow hairbands',
 ARRAY['Small Barbie doll'],
 ARRAY['Minor (under 12)'], true,
 'Nomvula Ndlovu (Mother)','+27 84 555 0103',
 ARRAY['https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=600&q=80'], now() - interval '3 days'),

('Sipho Ngcobo', 22, 'Male', 'Black African', 178, 75, 'Athletic',
 'Black short', 'Brown', 'Dark', ARRAY['Scar on right knee'],
 ARRAY['Depression'], false, ARRAY['On medication'],
 'voluntary','Sipho left home after argument with parents. Family concerned about his mental health.',
 'Yeoville, Johannesburg', now() - interval '12 days', 'Blue jeans, white t-shirt, black hoodie, sneakers',
 ARRAY['Black backpack','Phone','Wallet'],
 ARRAY['Mental health concerns'], false,
 'Themba Ngcobo (Father)','+27 82 555 0104',
 ARRAY['https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=600&q=80'], now() - interval '12 days'),

('Anna van Wyk', 72, 'Female', 'White', 158, 62, 'Average',
 'Grey short', 'Green', 'Fair', ARRAY['Wears glasses','Wedding ring on left hand'],
 ARRAY['Alzheimer''s disease','High blood pressure'], true, ARRAY['Requires constant supervision'],
 'medical','Mrs van Wyk walked out of her home in the early morning. Has been disoriented before but always returned.',
 'Brackenfell, Cape Town', now() - interval '2 days', 'Floral dress, beige cardigan, comfortable shoes',
 ARRAY['Handbag (left behind)'],
 ARRAY['Elderly','Cognitive impairment'], true,
 'Pieter van Wyk (Son)','+27 82 555 0105',
 ARRAY['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&q=80'], now() - interval '2 days'),

('Thabo Maseko', 14, 'Male', 'Black African', 160, 45, 'Slim',
 'Black short', 'Brown', 'Dark', ARRAY['Scar above left eyebrow from sport injury'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'family_conflict','Thabo left after argument with stepfather. Has run away once before but returned within 2 days.',
 'Mamelodi East, Pretoria', now() - interval '6 days', 'School uniform - white shirt, grey trousers, black shoes',
 ARRAY['School bag','Cellphone'],
 ARRAY['Minor (teen)'], false,
 'Beauty Maseko (Mother)','+27 83 555 0106',
 ARRAY['https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&q=80'], now() - interval '6 days'),

('Precious Khumalo', 4, 'Female', 'Black African', 105, 18, 'Slim',
 'Black short', 'Brown', 'Dark', ARRAY['Small mole on forehead'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'endangered','Precious was at the local park with her older sister when she went missing.',
 'Alexandra, Johannesburg', now() - interval '8 hours', 'Yellow t-shirt, blue shorts, pink sandals',
 ARRAY[]::text[],
 ARRAY['Minor (under 12)','Very young'], true,
 'Zanele Khumalo (Mother)','+27 84 555 0107',
 ARRAY['https://images.unsplash.com/photo-1543342384-1f1350e27861?w=600&q=80'], now() - interval '8 hours'),

('Vusi Dube', 35, 'Male', 'Black African', 180, 84, 'Athletic',
 'Black short', 'Brown', 'Dark', ARRAY['Tattoo of dove on left forearm'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'unknown','Vusi failed to return from work on Friday evening. Has not made contact with family.',
 'Sandton, Johannesburg', now() - interval '4 days', 'Black suit, white shirt, no tie',
 ARRAY['Laptop bag','Phone','Car keys'],
 ARRAY[]::text[], false,
 'Nokuthula Dube (Wife)','+27 82 555 0108',
 ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80'], now() - interval '4 days'),

('Khanyi Zulu', 19, 'Female', 'Black African', 167, 60, 'Slim',
 'Black braids', 'Brown', 'Medium', ARRAY['Pierced nose'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'voluntary','Khanyi left university residence without taking her belongings. Suspected to be with romantic interest.',
 'University of KZN, Durban', now() - interval '15 days', 'Casual clothing - jeans and pink top',
 ARRAY['Phone','Small backpack'],
 ARRAY[]::text[], false,
 'Nomusa Zulu (Mother)','+27 83 555 0109',
 ARRAY['https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&q=80'], now() - interval '15 days'),

('Daniel Coetzee', 11, 'Male', 'White', 145, 38, 'Average',
 'Blonde', 'Blue', 'Fair', ARRAY['Front tooth chipped'],
 ARRAY['Autism spectrum disorder'], true, ARRAY['Non-verbal in stressful situations','Wears medical ID bracelet'],
 'endangered','Daniel wandered from school grounds during break. Has a fascination with trains.',
 'Krugersdorp Primary School', now() - interval '6 hours', 'School uniform - grey shorts, white shirt',
 ARRAY['School bag'],
 ARRAY['Minor (under 12)','Cognitive impairment'], true,
 'Susan Coetzee (Mother)','+27 82 555 0110',
 ARRAY['https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80'], now() - interval '6 hours'),

('Sibongile Mthembu', 45, 'Female', 'Black African', 165, 72, 'Heavy',
 'Black weave', 'Brown', 'Dark', ARRAY['Surgical scar on left arm'],
 ARRAY['Bipolar disorder','High blood pressure'], false, ARRAY['Requires daily medication'],
 'medical','Sibongile stopped taking medication and disappeared during manic episode.',
 'Tembisa, Johannesburg', now() - interval '7 days', 'Red and black dress, sandals',
 ARRAY[]::text[],
 ARRAY['Mental health concerns','Medical condition'], true,
 'Bonisile Mthembu (Sister)','+27 84 555 0111',
 ARRAY['https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80'], now() - interval '7 days'),

('Riaan Botha', 67, 'Male', 'White', 174, 78, 'Average',
 'Bald with white sides', 'Hazel', 'Fair', ARRAY['Pacemaker scar on chest'],
 ARRAY['Heart condition','Diabetes'], false, ARRAY['Requires daily medication'],
 'medical','Mr Botha went for his morning walk and did not return. Believed to have suffered medical event.',
 'Hartbeespoort Dam area', now() - interval '2 days', 'Khaki shorts, white t-shirt, walking shoes, sun hat',
 ARRAY['Walking stick'],
 ARRAY['Elderly','Medical condition'], true,
 'Annetjie Botha (Wife)','+27 82 555 0112',
 ARRAY['https://images.unsplash.com/photo-1463453091185-61582044d556?w=600&q=80'], now() - interval '2 days'),

('Tumi Mokoena', 17, 'Female', 'Black African', 163, 55, 'Slim',
 'Black braids', 'Brown', 'Medium', ARRAY['Cross necklace usually worn'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'family_conflict','Tumi left after fight with mother over boyfriend. Has friends in another township.',
 'Soweto', now() - interval '20 days', 'Blue jeans, white sneakers, pink top',
 ARRAY['Phone','Small handbag'],
 ARRAY['Minor (teen)'], false,
 'Pretty Mokoena (Mother)','+27 83 555 0113',
 ARRAY['https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?w=600&q=80'], now() - interval '20 days'),

('Tshepo Modise', 6, 'Male', 'Black African', 115, 22, 'Slim',
 'Black short', 'Brown', 'Dark', ARRAY['Small birthmark on right cheek'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'endangered','Tshepo was taken from his bed during a home invasion. Suspected abduction.',
 'Atteridgeville, Pretoria', now() - interval '36 hours', 'Spider-Man pyjamas',
 ARRAY[]::text[],
 ARRAY['Minor (under 12)','Possible abduction'], true,
 'Lerato Modise (Mother)','+27 82 555 0114',
 ARRAY['https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=600&q=80'], now() - interval '36 hours'),

('Amanda Naidoo', 38, 'Female', 'Indian South African', 165, 68, 'Average',
 'Black long', 'Brown', 'Olive', ARRAY['Wedding ring','Henna tattoo on right hand'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'unknown','Amanda went shopping at the mall and never returned. Vehicle found in parking.',
 'Pavilion Shopping Centre, Westville', now() - interval '5 days', 'Floral kurta, jeans, sandals',
 ARRAY['Handbag','Car keys','Phone (off)'],
 ARRAY[]::text[], true,
 'Suresh Naidoo (Husband)','+27 84 555 0115',
 ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&q=80'], now() - interval '5 days'),

('Bongani Sithole', 28, 'Male', 'Black African', 176, 73, 'Athletic',
 'Black short', 'Brown', 'Medium', ARRAY['Tattoo of mother''s name on left arm'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'voluntary','Bongani left job and rented accommodation. Mental health crisis suspected.',
 'Cape Town CBD', now() - interval '45 days', 'Unknown - took most belongings',
 ARRAY['Backpack with clothes','Phone'],
 ARRAY['Mental health concerns'], false,
 'Nokuthula Sithole (Sister)','+27 82 555 0116',
 ARRAY['https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&q=80'], now() - interval '45 days'),

('Maria Santos', 81, 'Female', 'Portuguese', 152, 58, 'Slim',
 'White short', 'Brown', 'Olive', ARRAY['Wears glasses','Rosary in hand'],
 ARRAY['Severe dementia'], true, ARRAY['Needs constant supervision','Speaks Portuguese primarily'],
 'medical','Mrs Santos wandered from family home in the morning.',
 'Bedfordview, Johannesburg', now() - interval '18 hours', 'Long black dress, black cardigan, brown shoes',
 ARRAY[]::text[],
 ARRAY['Elderly','Cognitive impairment','Language barrier'], true,
 'Manuel Santos (Son)','+27 83 555 0117',
 ARRAY['https://images.unsplash.com/photo-1559963110-71b394e7494d?w=600&q=80'], now() - interval '18 hours'),

('Jabu Mahlangu', 25, 'Male', 'Black African', 181, 80, 'Athletic',
 'Black short', 'Brown', 'Dark', ARRAY['Birthmark on neck'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'unknown','Jabu went to a friend''s party and never returned home. Friends report he left around midnight.',
 'Vilakazi Street, Soweto', now() - interval '10 days', 'Black jeans, white shirt, blue blazer',
 ARRAY['Phone','Wallet'],
 ARRAY[]::text[], false,
 'Sandile Mahlangu (Brother)','+27 82 555 0118',
 ARRAY['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&q=80'], now() - interval '10 days'),

('Kgomotso Phiri', 13, 'Female', 'Black African', 152, 42, 'Slim',
 'Black braids', 'Brown', 'Medium', ARRAY['Wears glasses'],
 ARRAY['Severe asthma'], false, ARRAY['Requires inhaler at all times'],
 'endangered','Kgomotso did not arrive home from school. Last seen accepting lift from unknown vehicle.',
 'Olievenhoutbosch, Centurion', now() - interval '2 days', 'School uniform - blue dress, white shirt',
 ARRAY['School bag with books','Inhaler'],
 ARRAY['Minor (teen)','Medical condition'], true,
 'Refilwe Phiri (Mother)','+27 84 555 0119',
 ARRAY['https://images.unsplash.com/photo-1542596594-649edbc13630?w=600&q=80'], now() - interval '2 days'),

('Hennie de Wet', 55, 'Male', 'White', 178, 95, 'Heavy',
 'Brown/grey', 'Blue', 'Fair', ARRAY['Beard','Wedding ring','Tattoo of anchor on right arm'],
 ARRAY['Depression'], false, ARRAY['On medication'],
 'voluntary','Hennie left after losing job. Wife concerned about his mental state.',
 'Bloemfontein', now() - interval '25 days', 'Khaki pants, blue shirt, brown jacket',
 ARRAY['Backpack','Wallet','Phone'],
 ARRAY['Mental health concerns'], false,
 'Marlene de Wet (Wife)','+27 82 555 0120',
 ARRAY['https://images.unsplash.com/photo-1463453091185-61582044d556?w=600&q=80'], now() - interval '25 days'),

('Aaliyah Patel', 9, 'Female', 'Indian South African', 132, 30, 'Slim',
 'Black long', 'Brown', 'Olive', ARRAY['Small mole near right eye'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'endangered','Aaliyah was walking to corner shop alone when she disappeared.',
 'Phoenix, Durban', now() - interval '12 hours', 'Yellow dress, white sandals',
 ARRAY['R20 cash','Small purse'],
 ARRAY['Minor (under 12)'], true,
 'Reshma Patel (Mother)','+27 83 555 0121',
 ARRAY['https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=600&q=80'], now() - interval '12 hours'),

('Lwazi Mbeki', 30, 'Male', 'Black African', 177, 75, 'Athletic',
 'Black short', 'Brown', 'Medium', ARRAY['Tribal tattoo on right shoulder'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'unknown','Lwazi was driving home from work when contact was lost. Vehicle found abandoned on side of road.',
 'N3 between Harrismith and Durban', now() - interval '6 days', 'Blue jeans, t-shirt, sneakers',
 ARRAY['Wallet found in vehicle'],
 ARRAY[]::text[], true,
 'Nokuthula Mbeki (Wife)','+27 82 555 0122',
 ARRAY['https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&q=80'], now() - interval '6 days'),

('Elsie Nkosi', 70, 'Female', 'Black African', 160, 65, 'Average',
 'Grey short', 'Brown', 'Dark', ARRAY['Walking stick','Wears glasses'],
 ARRAY['Diabetes','Mild dementia'], true, ARRAY['Requires daily insulin'],
 'medical','Elsie left her home to visit neighbour and lost her way.',
 'Mofolo, Soweto', now() - interval '3 days', 'Black dress, white headscarf, comfortable shoes',
 ARRAY['Handbag with medication'],
 ARRAY['Elderly','Cognitive impairment','Medical condition'], true,
 'Lerato Nkosi (Daughter)','+27 84 555 0123',
 ARRAY['https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80'], now() - interval '3 days'),

('Tariq Achmat', 16, 'Male', 'Cape Coloured', 172, 60, 'Slim',
 'Black short', 'Brown', 'Olive', ARRAY['Acne scarring'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'family_conflict','Tariq left after argument about gang involvement. Family fears he has joined gang.',
 'Manenberg, Cape Town', now() - interval '14 days', 'Black tracksuit, white sneakers',
 ARRAY['Phone','Cash'],
 ARRAY['Minor (teen)','Possible gang involvement'], true,
 'Fatima Achmat (Mother)','+27 82 555 0124',
 ARRAY['https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?w=600&q=80'], now() - interval '14 days'),

('Naledi Tau', 21, 'Female', 'Black African', 168, 58, 'Athletic',
 'Black braids', 'Brown', 'Dark', ARRAY['Small scar on left knee'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'unknown','Naledi did not return from evening jog in residential area.',
 'Centurion', now() - interval '4 days', 'Black leggings, pink running top, running shoes',
 ARRAY['Earphones','Phone'],
 ARRAY[]::text[], true,
 'Tebogo Tau (Father)','+27 83 555 0125',
 ARRAY['https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&q=80'], now() - interval '4 days'),

('Christopher van Zyl', 12, 'Male', 'White', 148, 40, 'Slim',
 'Brown short', 'Green', 'Fair', ARRAY['Wears braces'],
 ARRAY['Type 1 Diabetes'], false, ARRAY['Requires insulin every 4 hours'],
 'endangered','Christopher disappeared from a sleepover at friend''s house.',
 'Randburg, Johannesburg', now() - interval '24 hours', 'Pyjamas - red and blue Spider-Man',
 ARRAY['Insulin pump (still attached)','Phone'],
 ARRAY['Minor (under 12)','Medical condition'], true,
 'Anel van Zyl (Mother)','+27 82 555 0126',
 ARRAY['https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80'], now() - interval '24 hours'),

('Themba Khumalo', 50, 'Male', 'Black African', 180, 88, 'Heavy',
 'Black/grey', 'Brown', 'Dark', ARRAY['Scar on left temple'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'unknown','Themba was last seen leaving his workplace. Has not contacted family.',
 'Germiston, Johannesburg', now() - interval '30 days', 'Workshop overalls, safety boots',
 ARRAY['Lunchbox','Wallet','Phone'],
 ARRAY[]::text[], false,
 'Sibongile Khumalo (Wife)','+27 84 555 0127',
 ARRAY['https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=600&q=80'], now() - interval '30 days'),

('Aisha Mohamed', 5, 'Female', 'Cape Malay', 110, 19, 'Slim',
 'Black long', 'Brown', 'Olive', ARRAY['Pierced ears with small gold studs'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'endangered','Aisha disappeared from preschool playground during outdoor play.',
 'Bo-Kaap, Cape Town', now() - interval '20 hours', 'Pink dress, white headscarf, pink shoes',
 ARRAY[]::text[],
 ARRAY['Minor (under 12)','Very young'], true,
 'Yasmin Mohamed (Mother)','+27 82 555 0128',
 ARRAY['https://images.unsplash.com/photo-1543342384-1f1350e27861?w=600&q=80'], now() - interval '20 hours'),

('Pieter Smit', 42, 'Male', 'White', 175, 82, 'Athletic',
 'Brown short', 'Hazel', 'Fair', ARRAY['Tattoo of springbok on left arm'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'voluntary','Pieter left after going through divorce. Possessions removed from home.',
 'Pretoria East', now() - interval '60 days', 'Unknown',
 ARRAY['Took car','Personal documents'],
 ARRAY[]::text[], false,
 'Annelie Smit (Sister)','+27 83 555 0129',
 ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80'], now() - interval '60 days'),

('Mpho Sebola', 18, 'Female', 'Black African', 165, 56, 'Slim',
 'Black braids', 'Brown', 'Medium', ARRAY['Small tattoo of star on right wrist'],
 ARRAY[]::text[], false, ARRAY[]::text[],
 'voluntary','Mpho left home after matric to find work in Johannesburg. Last contact 8 weeks ago.',
 'Park Station, Johannesburg', now() - interval '55 days', 'Last seen in jeans and red top',
 ARRAY['Bag with clothes','Phone (no signal)'],
 ARRAY[]::text[], false,
 'Mmatshepo Sebola (Mother)','+27 84 555 0130',
 ARRAY['https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=600&q=80'], now() - interval '55 days');
